// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsdwccuxybkjrxknmvij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzZHdjY3V4eWJranJ4a25tdmlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwODQ5OTEsImV4cCI6MjA1MzY2MDk5MX0.T4_Df99TFTz-7OrtkNBAO5qeXm-mK5LPuc5Wz5QAFLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);